package api.simplified.skyblock.model;

import com.google.gson.annotations.SerializedName;
import dev.simplified.collection.Concurrent;
import dev.simplified.collection.ConcurrentList;
import dev.simplified.persistence.JpaModel;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import lombok.Getter;
import org.jetbrains.annotations.NotNull;

import java.util.Objects;

/**
 * One stat line a potato book adds, scoped to a group of item types. Applying a book to a weapon
 * and to a piece of armour grants different stats, and that difference is what these rows carry.
 *
 * <p>
 * No lines are supplied today, so a lookup finds nothing until the data source carries them.
 */
@Getter
@Entity
@Table(name = "hot_potato_stats")
public class HotPotatoStat implements JpaModel {

    /**
     * Surrogate key generated by the schema, since a line carries no id of its own.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false)
    private long id;

    /**
     * Which book tier or family the line belongs to, so that the lines of one book read together.
     * It is the only thing separating a hot potato book from a fuming potato book.
     */
    @Column(name = "group_key", nullable = false)
    private @NotNull String groupKey = "";

    /**
     * Id of the stat granted, bound from the {@code stat} key.
     */
    @SerializedName("stat")
    @Column(name = "stat_id", nullable = false)
    private @NotNull String statId = "";

    /**
     * The item types this line applies to.
     */
    @Column(name = "item_types", nullable = false)
    private @NotNull ConcurrentList<String> itemTypes = Concurrent.newList();

    /**
     * Amount of the stat granted per book applied.
     */
    @Column(name = "value", nullable = false)
    private int value = 0;

    /**
     * The {@link Stat} resolved from {@link #statId}, mapped read-only onto the same column.
     */
    @ManyToOne
    @JoinColumn(name = "stat_id", referencedColumnName = "id", insertable = false, updatable = false)
    private Stat stat;

    @Override
    public boolean equals(Object o) {
        if (o == null || getClass() != o.getClass()) return false;

        HotPotatoStat that = (HotPotatoStat) o;

        return this.getId() == that.getId()
            && this.getValue() == that.getValue()
            && Objects.equals(this.getGroupKey(), that.getGroupKey())
            && Objects.equals(this.getStatId(), that.getStatId())
            && Objects.equals(this.getItemTypes(), that.getItemTypes());
    }

    @Override
    public int hashCode() {
        return Objects.hash(this.getId(), this.getGroupKey(), this.getStatId(), this.getItemTypes(), this.getValue());
    }

}
